# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_modular_headers!

target 'csci571-hw9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for csci571-hw9
  pod 'McPicker'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.4.0'
  pod 'SwiftSpinner'
  pod 'Toast-Swift', '~> 4.0.0'

end
